/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import apresentacao.TelaGrupos;
import persistencia.ComunicacaoServer;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.UnknownHostException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author lucas
 */
public class TelaLogin extends javax.swing.JFrame {

    ComunicacaoServer conn = null;
    Locale location;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        try {
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
        } catch (Exception e) {
            System.out.println("Sem lookfeel");
        }
        conn = new ComunicacaoServer();
        initComponents();
        this.preenche();       
        this.FieldEmail.setText("lucas");
        this.FieldPassword.setText("teste");
    }

    public static void main(String[] args) {
        TelaLogin tl = new TelaLogin();
        tl.setTitle("Research.Net - Login");
        tl.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelEmail = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        FieldEmail = new javax.swing.JTextField();
        FieldPassword = new javax.swing.JPasswordField();
        ButtonLogin = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        ButtonCreate = new javax.swing.JButton();
        LabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelEmail.setText("Email");

        LabelPassword.setText("Password");

        FieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldEmailKeyPressed(evt);
            }
        });

        FieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldPasswordKeyPressed(evt);
            }
        });

        ButtonLogin.setText("Login");
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Cancel");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        ButtonCreate.setText("Create");
        ButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPassword)
                    .addComponent(LabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldPassword)
                    .addComponent(FieldEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCreate))
                    .addComponent(LabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(FieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPassword)
                    .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLogin)
                    .addComponent(ButtonCancel)
                    .addComponent(ButtonCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static String md5(String str) {
        MessageDigest md;
        try {
            md = MessageDigest.getInstance("MD5");

            md.update(str.getBytes());
            byte[] bytes = md.digest();
            StringBuilder s = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                int parteAlta = ((bytes[i] >> 4) & 0xf) << 4;
                int parteBaixa = bytes[i] & 0xf;
                if (parteAlta == 0) {
                    s.append('0');
                }
                s.append(Integer.toHexString(parteAlta | parteBaixa));
            }
            return s.toString();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        if (conn.conectar()) {
            ButtonLogin.setEnabled(false);
            //String hash = md5(FieldEmail.getText() + new String(FieldPassword.getPassword()));
            String hash = md5(new String(FieldPassword.getPassword()));
            
            conn.send(FieldEmail.getText() + "/" + hash, ComunicacaoServer.LOGIN);
            Thread tmp = new Thread(
                    new Runnable() {

                @Override
                public void run() {
                    boolean tmp;
                    while (conn.receiving) {
                    }
                    ButtonLogin.setEnabled(true);
                    if (ComunicacaoServer.LOGIN_ACCEPTED.equals(conn.msg)) {
                        callNextWindow();
                    } else {
                        
                        LabelStatus.setText("Wrong User and/or Password");
                    }

                }
            });
            tmp.start();
        } else {
            LabelStatus.setText("Connection Failed");
        }
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void ButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateActionPerformed
        ButtonCreate.setEnabled(false);
        String hash = md5(FieldEmail.getText() + new String(FieldPassword.getPassword()));
        conn.send(FieldEmail.getText() + "/" + hash, ComunicacaoServer.CREATE_USER);
        Thread tmp = new Thread(
                new Runnable() {

            @Override
            public void run() {
                boolean tmp;
                while (conn.receiving) {
                }
                ButtonCreate.setEnabled(true);
                if (ComunicacaoServer.USER_CREATED.equals(conn.msg)) {
                    LabelStatus.setText("User Created");
                } else if (ComunicacaoServer.USED_EMAIL.equals(conn.msg)) {
                    LabelStatus.setText("Email Already Used");
                }

            }
        });
        tmp.start();
    }//GEN-LAST:event_ButtonCreateActionPerformed

    private void FieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ButtonLoginActionPerformed(null);
        }
    }//GEN-LAST:event_FieldEmailKeyPressed

    private void FieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ButtonLoginActionPerformed(null);
        }
    }//GEN-LAST:event_FieldPasswordKeyPressed

    private void callNextWindow() {
        this.dispose();
        System.out.println("TELALOGIN:callWindow"+new String[0]);
        //guiGrafo.main(new String[0]);
        //TelaGrupos.main(new String[0]);
        System.out.println("TelaLogin: chamando tela grupos...");
        TelaGrupos tg = new TelaGrupos(this.conn, this.location);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonCreate;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JTextField FieldEmail;
    private javax.swing.JPasswordField FieldPassword;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelStatus;
    // End of variables declaration//GEN-END:variables

    private void preenche() {
        location = new Locale("pt", "BR");
        ResourceBundle msg = ResourceBundle.getBundle("resources/msgs", location);
        LabelPassword.setText(msg.getString("senha"));
        ButtonCancel.setText(msg.getString("cancelar"));
        ButtonCreate.setText(msg.getString("criar"));
    }
}
