/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import negocio.HotTubeOnOffCommand;
import negocio.Command;
import negocio.Controle2Slot;
import negocio.HotTube;
import negocio.Light;
import negocio.Tv;
import negocio.TvOnOffCommand;
import negocio.TvOnOffLightOnOffCommand;

/**
 *
 * @author iapereira
 */
public class ControleSwing extends javax.swing.JFrame {

    private final Controle2Slot controle;

    /**
     * Creates new form ControleSwing
     */
    public ControleSwing() {
        initComponents();
         Tv tv = new Tv();
         Light light = new Light();
         HotTube hotTube = new HotTube();
        
        //Command slot1 = new TvOnOffCommand(tv);
        Command slot1 = new TvOnOffLightOnOffCommand(tv, light);
        Command slot2 = new HotTubeOnOffCommand(hotTube);
        
        controle = new Controle2Slot(slot1, slot2);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slot1botaoOn = new javax.swing.JButton();
        slot1BotaoOff = new javax.swing.JButton();
        slot1Nome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        slot2BotaoOn = new javax.swing.JButton();
        slot2BotaoOff = new javax.swing.JButton();
        slot1BotaoMiddle = new javax.swing.JButton();
        slot2BotaoMiddle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        slot1botaoOn.setText("On");
        slot1botaoOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slot1botaoOnActionPerformed(evt);
            }
        });

        slot1BotaoOff.setText("Off");
        slot1BotaoOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slot1BotaoOffActionPerformed(evt);
            }
        });

        slot1Nome.setText("Tv/Light");

        jLabel1.setText("HotTube");

        slot2BotaoOn.setText("On");
        slot2BotaoOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slot2BotaoOnActionPerformed(evt);
            }
        });

        slot2BotaoOff.setText("Off");
        slot2BotaoOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slot2BotaoOffActionPerformed(evt);
            }
        });

        slot1BotaoMiddle.setText("Middle");
        slot1BotaoMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slot1BotaoMiddleActionPerformed(evt);
            }
        });

        slot2BotaoMiddle.setText("Middle");
        slot2BotaoMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slot2BotaoMiddleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slot1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(slot1botaoOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot1BotaoMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot1BotaoOff)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot2BotaoOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot2BotaoMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot2BotaoOff)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slot1botaoOn)
                    .addComponent(slot1BotaoOff)
                    .addComponent(slot1Nome)
                    .addComponent(slot1BotaoMiddle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(slot2BotaoOn)
                    .addComponent(slot2BotaoOff)
                    .addComponent(slot2BotaoMiddle))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slot1botaoOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slot1botaoOnActionPerformed
        // TODO add your handling code here:
        controle.buttonOn(1);
    }//GEN-LAST:event_slot1botaoOnActionPerformed

    private void slot1BotaoOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slot1BotaoOffActionPerformed
        // TODO add your handling code here:
        controle.buttonOff(1);
    }//GEN-LAST:event_slot1BotaoOffActionPerformed

    private void slot2BotaoOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slot2BotaoOnActionPerformed
        // TODO add your handling code here:
        controle.buttonOn(2);

    }//GEN-LAST:event_slot2BotaoOnActionPerformed

    private void slot2BotaoOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slot2BotaoOffActionPerformed
        // TODO add your handling code here:
        controle.buttonOff(2);

    }//GEN-LAST:event_slot2BotaoOffActionPerformed

    private void slot1BotaoMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slot1BotaoMiddleActionPerformed
        // TODO add your handling code here:
        controle.buttonMiddle(1);
    }//GEN-LAST:event_slot1BotaoMiddleActionPerformed

    private void slot2BotaoMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slot2BotaoMiddleActionPerformed
        // TODO add your handling code here:
        controle.buttonMiddle(2);

    }//GEN-LAST:event_slot2BotaoMiddleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton slot1BotaoMiddle;
    private javax.swing.JButton slot1BotaoOff;
    private javax.swing.JLabel slot1Nome;
    private javax.swing.JButton slot1botaoOn;
    private javax.swing.JButton slot2BotaoMiddle;
    private javax.swing.JButton slot2BotaoOff;
    private javax.swing.JButton slot2BotaoOn;
    // End of variables declaration//GEN-END:variables
}
