/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * guiReplicas.java
 *
 * Created on 30/11/2011, 21:05:33
 */
package apresentacao;

import persistencia.ConexaoPostgreSQL;
import negocio.Aresta;
import negocio.Publicacao;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class guiRepresentacoes extends javax.swing.JFrame {
    Publicacao pub1;
    Publicacao pub2;
    int ultimoUpdate;

    /** Creates new form guiReplicas */
    public guiRepresentacoes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("As referências bibliográficas acima referenciam a mesma produção científica?");

        jButton1.setText("Yes");
        jButton1.setPreferredSize(new java.awt.Dimension(74, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("No");
        jButton2.setMaximumSize(new java.awt.Dimension(74, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(74, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(74, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.setAlignmentY(0.0F);
        jButton4.setPreferredSize(new java.awt.Dimension(74, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ConexaoPostgreSQL conexao = new ConexaoPostgreSQL();
        String query="UPDATE versionado.replica SET f_cont=f_cont+1 WHERE id1="+pub1.id_publicacao+" and id2="+pub2.id_publicacao+" and versao = (select atual from versao)";
        conexao.executeUpdate(query);
        conexao.close();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);      
        jButton3.setEnabled(true);
        ultimoUpdate=1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConexaoPostgreSQL conexao = new ConexaoPostgreSQL();
        String query="UPDATE versionado.replica SET v_cont=v_cont+1 WHERE id1="+pub1.id_publicacao+" and id2="+pub2.id_publicacao+" and versao = (select atual from versao)";
        conexao.executeUpdate(query);
        conexao.close();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(true);
        ultimoUpdate=0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ConexaoPostgreSQL conexao = new ConexaoPostgreSQL();
        if(ultimoUpdate==0)
        {
            String query="UPDATE versionado.replica SET v_cont=v_cont-1 WHERE id1="+pub1.id_publicacao+" and id2="+pub2.id_publicacao+" and versao = (select atual from versao)";
            conexao.executeUpdate(query);
        }
        else if(ultimoUpdate==1)
        {
            String query="UPDATE versionado.replica SET f_cont=f_cont-1 WHERE id1="+pub1.id_publicacao+" and id2="+pub2.id_publicacao+" and versao = (select atual from versao)";
            conexao.executeUpdate(query);
        }

        conexao.close();
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiReplicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiReplicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiReplicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiReplicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new guiRepresentacoes().setVisible(true);
            }
        });
    }
    
    
    public void preenche(int clicked, Aresta ar){
        String query;
        
        ResourceBundle msg = ResourceBundle.getBundle("resources/msgs", TelaGrafo.location);
  
        //aresta ar = guiGrafo.getAresta();
        List<Publicacao> listaImprime = ar.getListaImprime();
        String[] coluna = new String[1];
        
        pub1 = listaImprime.get(clicked);
        pub2 = pub1.replica;
        
        coluna[0]=msg.getString("artigos");
        String[][] data = new String[2][1];
        
        data[0][0] = msg.getString("curriculoOrigem")+": " + pub1.nome_membro +"\n"+pub1.toString();
        data[1][0] = msg.getString("curriculoOrigem")+": " + pub2.nome_membro +"\n"+pub2.toString();
        
        
        
        
        DefaultTableModel model = new DefaultTableModel(data,coluna){
            @Override
            public boolean isCellEditable(int rowIndex, int mColIndex) {  
                return false;  
            } 
        };
        
        
        jLabel1.setText(msg.getString("perguntaValidacao"));
            
        jTable2.setModel(model);
        
        jTable2.getColumnModel().getColumn(0).setCellRenderer(new TableCellLongTextRenderer()); 
          
//              
//        //comunicacao conexao = new ConnBanco();        
//        if(value=="Sim"){
//            //query="UPDATE replica SET v_cont=v_cont+1 WHERE id1="+pub1.id_publicacao+" and id2="+pub2.id_publicacao;
//            //conexao.executeUpdate(query);
//            System.out.println("Sim");
//        }
//        else if(value=="Não")
//        {
//            //query="UPDATE replica SET f_cont=f_cont+1 WHERE id1="+pub1.id_publicacao+" and id2="+pub2.id_publicacao;
//            //conexao.executeUpdate(query);
//            System.out.println("Nao");
//        }
//        else if(value=="Fechar")
//        {
//            System.out.println("Fechar");
//        }
//        //conexao.close();
        
        jButton1.setText(msg.getString("sim"));
        jButton2.setText(msg.getString("nao"));
        jButton3.setText(msg.getString("cancelar"));
        jButton4.setText(msg.getString("fechar"));
        
        setTitle(msg.getString("tituloValidacao"));
        
    }
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
